### PR TITLE
Adding unit test cases

### PR DESCRIPTION
**Pull request by prakharbhatt007**
# Mbed Edge pull request

`
1. Added Unit Test
2. Change cmake files to create unit test builds.

`

## Description

`1. Added Unit Test
2. Change cmake files to create unit test builds.
`

## Test instructions

`Submitter: Please add instructions to test your PR here.`

`If your pull request is a fix for a defect please write instructions
to reproduce the defect.`

### API change(s)

 - [ ] Not applicable.
 - [ ] API is backwards compatible.
 - [ ] API documentation is updated.

### Example applications updated

 - [ ] Not applicable.

### CODE REVIEW

**Review by OPpuolitaival — APPROVED** [review]

**Review by esajaa — CHANGES_REQUESTED** [review]
- lib/cpputest library i missing (tests don't compile at the moment, at least on my test)
- build & running instructions missing (the flow isn't too obvious)

**Review by esajaa — APPROVED** [review]
Okay, noticed that the submodule is in another PR and the Makefile.test in third one, so I guess that fills the gaps there. I'd still recommend adding a section about running unit tests to the README

**Comment by ygoyal18** [comment]
Ya, we should kept everything related to unit test cases in one PR. It will be much easier to test.

**Review by OPpuolitaival — COMMENTED** [review]
Looks good. Let's add PR check for these when merged

**Review by ygoyal18 — APPROVED** [review]

**Pull request merged**
