### PR TITLE
Implement combined image callbacks for bootloader

### PR DESCRIPTION
**Pull request by davidsaada**
This PR implements the combined image callbacks for bootloader. This assumes that boot capsule update is implemented on the device.

### CODE REVIEW

**Comment by whygoyal** [comment]
@davidsaada Is this required for PE 2.5 release?

**Comment by davidsaada** [comment]
> @davidsaada Is this required for PE 2.5 release?

Not sure about that. This is required for ABB and should be part of the combined update and bootloader capsule update effort. If it is, then [ABB NGGW #29](https://github.com/PelionIoT/abb_nggw_G/pull/29) and [Meta mbed edge #74](https://github.com/PelionIoT/meta-mbed-edge/pull/74) should be merged together as well.

**Comment by whygoyal** [comment]
Okay. I will release a new version of edge-core once this is merged. 
@davidsaada Do you anticipate more PRs related to this feature?

**Comment by davidsaada** [comment]
> Okay. I will release a new version of edge-core once this is merged. @davidsaada Do you anticipate more PRs related to this feature?

@whygoyal Probably not in this repo, but in the surrounding ones asentioned above.

**Pull request merged**
